javac -cp .;..  CircleInFramebuffer.java
javac -cp .;..  DiagonalLineInFramebuffer.java
javac -cp .;..  Line_R1.java
javac -cp .;..  LineInViewport_R1.java
javac -cp .;..  Lines_R1.java
javac -cp .;..  LinesInTwoViewports_R1.java
javac -cp .;..  OfflineCube.java
javac -cp .;..  OfflineCubes.java
javac -cp .;..  OfflineGRS.java
javac -cp .;..  OfflineMovie.java
javac -cp .;..  OfflineTriangle.java
javac -cp .;..  SomethingWrong_1.java
javac -cp .;..  SomethingWrong_2.java
javac -cp .;..  ThreeDimensionalScene_R1.java
javac -cp .;..  TurtleGraphics.java

java  -cp .;..  CircleInFramebuffer
java  -cp .;..  DiagonalLineInFramebuffer
java  -cp .;..  Line_R1
java  -cp .;..  LineInViewport_R1
java  -cp .;..  Lines_R1
java  -cp .;..  LinesInTwoViewports_R1
java  -cp .;..  OfflineCube
java  -cp .;..  OfflineCubes
java  -cp .;..  OfflineGRS
java  -cp .;..  OfflineMovie
java  -cp .;..  OfflineTriangle
::java  -cp .;..  SomethingWrong_1
java  -cp .;..  SomethingWrong_2
java  -cp .;..  ThreeDimensionalScene_R1
java  -cp .;..  TurtleGraphics
pause
